name: Python application test

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_DB: dnd
          POSTGRES_USER: evan
          POSTGRES_PASSWORD: whowatchesthewatchmen
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Copy config
      run: cp config/github-credentials.yml config/db.yml
    - name: Start server
      run: python src/server.py &
    - name: Sleep for 3 seconds
      run: sleep 3
    - name: Run tests
      run: python -m unittest -v
